### ISSUE TITLE
Design interface  for the website ?

### ISSUE THREAD

**Issue by rubik18** [phuongvu0909/SEO4-Nhom14.2#10]
Thiết kế khung giao diện cho trang web

**Comment by phuongvu0909** [comment]
Mình có một ý tưởng về web này nhé#10
![image](https://user-images.githubusercontent.com/66147499/100124218-f59f2680-2ead-11eb-89e5-a0c855e81ac3.png)
![image](https://user-images.githubusercontent.com/66147499/100124275-064f9c80-2eae-11eb-875d-1cd34b03f15c.png)

**Comment by rubik18** [comment]
![Log in - Google Chrome 2020-12-28 4_16_11 PM](https://user-images.githubusercontent.com/59856402/103203781-4d570480-4928-11eb-98f3-606793680804.png)

Tài khoản: admin1
Mk: 0000
Các bạn cho ý kiến để mk hoàn thiện giao diện web nhé

**Comment by rubik18** [comment]
Đã update giao diện mới
