### ISSUE TITLE
released version 0.5 ?

### ISSUE THREAD

**Issue by rubik18** [phuongvu0909/SEO4-Nhom14.2#15]
Kết quả sơ bộ của dự án

**Comment by kaioz11** [comment]
mình đã tạo bản beta 0.5 bạn xem và đưa ý kiến

**Comment by kaioz11** [comment]
@rubik18 @phuongvu0909 các bạn kiểm tra version 0.5 đưa ý kiến

**Comment by rubik18** [comment]
Bản version 0.5 mới là bước đầu hoàn thiện sơ bộ phần khung của dự án, tạo cơ sở dữ liệu, thiết kế trang web, load file glb lên cơ sở dữ liệu, đọc và show file glb lên trang web. Tuy nhiên chưa liên kết hết lại với nhau được để đưa nội dung file glb lên cơ sở dữ liệu, thêm các chức năng với  web hiển thị file glb, hoàn thiện thiết kế trang web..... Nhóm sẽ tiếp tục thực hiện để đưa ra bản hoàn thiện cuối cùng tốt nhất có thể.

**Comment by rubik18** [comment]
Để chạy được chương trình demo 0.5 người dùng cần phải dowload file .zip về giải nén, import file model3l.sql lên cơ sở dữ liệu (cần có xamp để chạy cơ sở dữ liệu trên local), và đưa toàn bộ  folder  code vào htdocs của xamp rồi chạy trên local thì mới chạy được

**Comment by rubik18** [comment]
Tài khoản: admin1
Mk: 0000
Trên đây là tài khoản của trang web ạ

**Comment by thuynga2705** [comment]
bản version 0.5 chưa đưa được nội dung GLB lên cơ sở dữ liệu.

**Comment by kaioz11** [comment]
nội dung cập nhật bổ sung sẽ được đưa vào trong phiên bản tiếp theo
