### ISSUE TITLE
add some features

### ISSUE THREAD

**Issue by kaioz11** [phuongvu0909/SEO4-Nhom14.2#16]
@phuongvu0909 @rubik18 @thuynga2705 các bạn cho ý kiến đưa ra thêm một số tính năng mới cho phần nội dung về 3d để mình bổ sung trước khi hoàn thành

**Comment by thuynga2705** [comment]
>t đang tìm nhé

**Comment by phuongvu0909** [comment]
Mình nghĩ có thể bổ sung thêm tính năng chỉnh shadow cho nội dung 3d !#16

**Comment by kaioz11** [comment]
> Mình nghĩ có thể bổ sung thêm tính năng chỉnh shadow cho nội dung 3d !#16

ok, mình sẽ bổ sung

**Comment by phuongvu0909** [comment]
Bạn đẩy phần chức năng đó đã ổn chưa?

**Comment by kaioz11** [comment]
mình đã bổ sung thêm một số tính năng
- Thay đổi màu của obj
- Thay đổi vị trí cài đặt của ánh sáng
- Thay đổi màu của ánh sáng
- Thêm shadow cho obj
- Thêm raycas 
- Play/pause animation

Tất cả các phần đều đã hoạt động ổn định

**Comment by kaioz11** [comment]
Về phần shadow mình sẽ cải tiến thêm

**Comment by kaioz11** [comment]
Mình sẽ nghiên cứu bổ sung thêm một vài tính năng nữa
