### ISSUE TITLE
Run server and interface

### ISSUE THREAD

**Issue by kaioz11** [phuongvu0909/SEO4-Nhom14.2#17]
@rubik18 mình cần mô tả hướng dẫn khởi chạy chương trình phần server và giao diện

**Comment by phuongvu0909** [comment]
@rubik18

**Comment by rubik18** [comment]
Bạn tải toàn bộ code về nhé, yêu cầu bắt buộc bạn phải có server để chạy database , ở đây mình khuến khích dùng xamp 
- Đầu tiên trong localhost bạn tạo database mới có tên model3d rồi import file .sql trog folder csdl vào . 
- Sau đó đưa toàn bộ folder code vào folder htdocs của xamp. 
- Cuối cùng là chạy trên web với đường dẫn: [http://localhost/SEO4-Nhom14.2/webserver/login.php](url)
- Tài khoản và mật khẩu hiện tại là  (tk: admin ,mk: 0000) hoặc (tk: admin1  ,  mk: 1111) hoặc (tk:  admin2  ,  mk:  0000)

**Comment by kaioz11** [comment]
ok, đã chạy được
