### ISSUE TITLE
additional introduction of readme ? 

### ISSUE THREAD

**Issue by phuongvu0909** [phuongvu0909/SEO4-Nhom14.2#18]
Các bạn có thể cho ý kiến để mình hoàn thiện thêm phần readme được không?

**Comment by kaioz11** [comment]
Cần bổ sung thêm phần các chức năng  của obj

**Comment by kaioz11** [comment]
Mô tả về giao diện trang web

**Comment by kaioz11** [comment]
thêm cách cài đặt sử dụng nữa

**Comment by phuongvu0909** [comment]
Mình đã thêm các chức năng bạn bổ sung rồi nhé
