### ISSUE TITLE
Lỗi đường dẫn gọi file

### ISSUE THREAD

**Issue by rubik18** [phuongvu0909/SEO4-Nhom14.2#2]
Do các file gọi đến Mai để đường dẫn  tương đối nên mọi người pull code về không chạy được ( tổ chức thư mục ,tên thư mục trên máy mỗi người khác nhau mà)....===> Đổi sang đường dẫn tuyệt đối

**Comment by Kaioz-oh** [comment]
> Do các file gọi đến Mai để đường dẫn tương đối nên mọi người pull code về không chạy được ( tổ chức thư mục ,tên thư mục trên máy mỗi người khác nhau mà)....===> Đổi sang đường dẫn tuyệt đối

Bạn có thể chạy chương trình trên local web server, truy cập trang với http://localhost:
hoặc thay đổi đường dẫn files load models

**Comment by Kaioz-oh** [comment]
> Do the file call to Mai to the path, mọi người kéo code về không thể chạy được (thư mục tổ chức, thư mục tên trên máy tính của mỗi người khác nhau mà) .... ===> Change to the path path for

Bạn có thể tham khảo cách khắc phục tại đây:
https://threejs.org/docs/#manual/en/introduction/How-to-run-things-locally
