### ISSUE TITLE
What is database of project

### ISSUE THREAD

**Issue by kaioz11** [phuongvu0909/SEO4-Nhom14.2#3]
@phuongvu0909 Cập nhật khung cơ sở dữ liệu của dự án

**Comment by rubik18** [comment]
Vì cơ sở dữ liệu chạy trên local, nên sau khi upload thêm file lên thì các bạn export file sql mới ra và đưa vào folder nhé, chúng ta sẽ dùng file sql mới và đầy đủ nhất
