### ISSUE TITLE
File upload error

### ISSUE THREAD

**Issue by kaioz11** [phuongvu0909/SEO4-Nhom14.2#8]
Thực hiện tải lên files '.glb', báo lỗi: 
"Connected successfully
Thêm dữ liệu thất bại !"

**Comment by rubik18** [comment]
Bạn  update lại cơ sở dữ liệu mình đã push lên cùng với code thử xem, mình vừa test lại và vẫn upload file được bình thường mà, sau khi upload file glb tự động được thêm vào folder upload, và trên csdl thì lấy đường dẫn đến file vừa được thêm.

**Comment by rubik18** [comment]
Mình đã xem code , giờ có thể up load file glb và  có thể up cả file ảnh mô tả nữa nhé ( file ảnh này người dùng có thể up hoặc không)

**Comment by kaioz11** [comment]
ok
